AllCops:
  Include:
    - metadata.rb
    - '**/Gemfile'
    - attributes/**/*
    - libraries/**/*
    - recipes/**/*
    - spec/**/*
  Exclude:
    - cookbooks/**/*
    - vendor/**/*

Encoding:
  Exclude:
    - metadata.rb
    - Gemfile

NumericLiterals:
  Enabled: false

LineLength:
  Enabled: false

WordArray:
  MinSize: 3
